# Example configuration options that can be placed in your main SiriProxy config.yml

############################################
# NOTICE: Modifying these options in this 
#         file has no effect. You must put 
#         them in SiriProxy's config.yml!
############################################

    - name: 'Arduino' #don't touch
      path: 'https://github.com/rakusu/SiriProxy-TV-Control.git' #don't touch
